/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_CONFIG_PB_H_INCLUDED
#define PB_CONFIG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _WiFiConfigMessage {
    char ssid[16];
    char passphrase[16];
} WiFiConfigMessage;

typedef struct _MqttConfigMessage {
    char mqtt_server[24];
    uint32_t mqtt_port;
    char mqtt_user[16];
    char mqtt_pass[16];
} MqttConfigMessage;

typedef PB_BYTES_ARRAY_T(8) Ds18b20ConfigMessage_address_t;
typedef struct _Ds18b20ConfigMessage {
    Ds18b20ConfigMessage_address_t address;
    uint32_t output_pin;
} Ds18b20ConfigMessage;

typedef struct _RtcConfigMessage {
    char ntp_server[32];
    uint32_t timezone;
} RtcConfigMessage;

typedef struct _AppsConfigMessage {
    pb_size_t temperature_sensor_count;
    Ds18b20ConfigMessage temperature_sensor[4];
} AppsConfigMessage;

typedef struct _ConfigMessage {
    bool has_wifi_config;
    WiFiConfigMessage wifi_config;
    bool has_apps_config;
    AppsConfigMessage apps_config;
    bool has_mqtt_config;
    MqttConfigMessage mqtt_config;
    bool has_rtc_config;
    RtcConfigMessage rtc_config;
} ConfigMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define WiFiConfigMessage_init_default           {"", ""}
#define MqttConfigMessage_init_default           {"", 0, "", ""}
#define Ds18b20ConfigMessage_init_default        {{0, {0}}, 0}
#define RtcConfigMessage_init_default            {"", 0}
#define AppsConfigMessage_init_default           {0, {Ds18b20ConfigMessage_init_default, Ds18b20ConfigMessage_init_default, Ds18b20ConfigMessage_init_default, Ds18b20ConfigMessage_init_default}}
#define ConfigMessage_init_default               {false, WiFiConfigMessage_init_default, false, AppsConfigMessage_init_default, false, MqttConfigMessage_init_default, false, RtcConfigMessage_init_default}
#define WiFiConfigMessage_init_zero              {"", ""}
#define MqttConfigMessage_init_zero              {"", 0, "", ""}
#define Ds18b20ConfigMessage_init_zero           {{0, {0}}, 0}
#define RtcConfigMessage_init_zero               {"", 0}
#define AppsConfigMessage_init_zero              {0, {Ds18b20ConfigMessage_init_zero, Ds18b20ConfigMessage_init_zero, Ds18b20ConfigMessage_init_zero, Ds18b20ConfigMessage_init_zero}}
#define ConfigMessage_init_zero                  {false, WiFiConfigMessage_init_zero, false, AppsConfigMessage_init_zero, false, MqttConfigMessage_init_zero, false, RtcConfigMessage_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define WiFiConfigMessage_ssid_tag               1
#define WiFiConfigMessage_passphrase_tag         2
#define MqttConfigMessage_mqtt_server_tag        1
#define MqttConfigMessage_mqtt_port_tag          2
#define MqttConfigMessage_mqtt_user_tag          3
#define MqttConfigMessage_mqtt_pass_tag          4
#define Ds18b20ConfigMessage_address_tag         1
#define Ds18b20ConfigMessage_output_pin_tag      2
#define RtcConfigMessage_ntp_server_tag          1
#define RtcConfigMessage_timezone_tag            2
#define AppsConfigMessage_temperature_sensor_tag 1
#define ConfigMessage_wifi_config_tag            1
#define ConfigMessage_apps_config_tag            2
#define ConfigMessage_mqtt_config_tag            3
#define ConfigMessage_rtc_config_tag             4

/* Struct field encoding specification for nanopb */
#define WiFiConfigMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              1) \
X(a, STATIC,   SINGULAR, STRING,   passphrase,        2)
#define WiFiConfigMessage_CALLBACK NULL
#define WiFiConfigMessage_DEFAULT NULL

#define MqttConfigMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   mqtt_server,       1) \
X(a, STATIC,   SINGULAR, UINT32,   mqtt_port,         2) \
X(a, STATIC,   SINGULAR, STRING,   mqtt_user,         3) \
X(a, STATIC,   SINGULAR, STRING,   mqtt_pass,         4)
#define MqttConfigMessage_CALLBACK NULL
#define MqttConfigMessage_DEFAULT NULL

#define Ds18b20ConfigMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    address,           1) \
X(a, STATIC,   SINGULAR, UINT32,   output_pin,        2)
#define Ds18b20ConfigMessage_CALLBACK NULL
#define Ds18b20ConfigMessage_DEFAULT NULL

#define RtcConfigMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ntp_server,        1) \
X(a, STATIC,   SINGULAR, UINT32,   timezone,          2)
#define RtcConfigMessage_CALLBACK NULL
#define RtcConfigMessage_DEFAULT NULL

#define AppsConfigMessage_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  temperature_sensor,   1)
#define AppsConfigMessage_CALLBACK NULL
#define AppsConfigMessage_DEFAULT NULL
#define AppsConfigMessage_temperature_sensor_MSGTYPE Ds18b20ConfigMessage

#define ConfigMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wifi_config,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  apps_config,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mqtt_config,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rtc_config,        4)
#define ConfigMessage_CALLBACK NULL
#define ConfigMessage_DEFAULT NULL
#define ConfigMessage_wifi_config_MSGTYPE WiFiConfigMessage
#define ConfigMessage_apps_config_MSGTYPE AppsConfigMessage
#define ConfigMessage_mqtt_config_MSGTYPE MqttConfigMessage
#define ConfigMessage_rtc_config_MSGTYPE RtcConfigMessage

extern const pb_msgdesc_t WiFiConfigMessage_msg;
extern const pb_msgdesc_t MqttConfigMessage_msg;
extern const pb_msgdesc_t Ds18b20ConfigMessage_msg;
extern const pb_msgdesc_t RtcConfigMessage_msg;
extern const pb_msgdesc_t AppsConfigMessage_msg;
extern const pb_msgdesc_t ConfigMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WiFiConfigMessage_fields &WiFiConfigMessage_msg
#define MqttConfigMessage_fields &MqttConfigMessage_msg
#define Ds18b20ConfigMessage_fields &Ds18b20ConfigMessage_msg
#define RtcConfigMessage_fields &RtcConfigMessage_msg
#define AppsConfigMessage_fields &AppsConfigMessage_msg
#define ConfigMessage_fields &ConfigMessage_msg

/* Maximum encoded size of messages (where known) */
#define AppsConfigMessage_size                   72
#define CONFIG_PB_H_MAX_SIZE                     ConfigMessage_size
#define ConfigMessage_size                       218
#define Ds18b20ConfigMessage_size                16
#define MqttConfigMessage_size                   65
#define RtcConfigMessage_size                    39
#define WiFiConfigMessage_size                   34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
