/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(WiFiConfigMessage, WiFiConfigMessage, AUTO)


PB_BIND(MqttConfigMessage, MqttConfigMessage, AUTO)


PB_BIND(Ds18b20ConfigMessage, Ds18b20ConfigMessage, AUTO)


PB_BIND(RtcConfigMessage, RtcConfigMessage, AUTO)


PB_BIND(AppsConfigMessage, AppsConfigMessage, AUTO)


PB_BIND(ConfigMessage, ConfigMessage, AUTO)



